install.packages('devtools')
devtools::install_github('cbroeckl/RAMClustR')
devtools::install_github('cbroeckl/csu.pmf.tools')
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("xcms")
install.packages('ClassDiscovery')
install.packages('PCDimension')
install.packages('ggfortify')
