#' pmf.defineExperiment
#'
#' set up exeperimental design and instrument description
#' @details differs from RAMClustR define experiment in having preconfigured instruments and slots for factor descriptiosn.
#' @return returns an R object suitable for use as an ExpDes input to ramclustR() function.  
#' @concept ramclustR
#' @concept RAMClustR

pmf.defineExperiment<-function()
{
  
  
  paramsets<-list(
    HilicPos=data.frame(c(chrominst="Waters UPLC: Sequant ZIC-pHILIC",
                          msinst="Waters Xevo G2 TOF",
                          column="Sequant ZIC-pHilic, 2 x 150 mm, 5 uM",
                          solvA="Water, 10 mM Ammomium Bicarbonate, pH 9.6",
                          solvB="Acetonitrile",
                          MSlevs=2,
                          CE1="6",
                          CE2="15-30",
                          mstype="TOF",
                          mzdifftof=0.05,
                          msmode="P",
                          ionization="ESI",
                          ESIvoltage="2200",
                          colgas="Ar",
                          msscanrange="50-1200",
                          conevolt="30")),
    
    HilicNeg=data.frame(c(chrominst="Waters UPLC: Sequant ZIC-pHILIC",
                          msinst="Waters Xevo G2 TOF",
                          column="Sequant ZIC-pHilic, 2 x 150 mm, 5 uM",
                          solvA="Water, 10 mM Ammomium Bicarbonate, pH 9.6",
                          solvB="Acetonitrile",
                          MSlevs=2,
                          CE1="6",
                          CE2="15-30",
                          mstype="TOF",
                          mzdifftof=0.05,
                          msmode="N",
                          ionization="ESI",
                          ESIvoltage="2200",
                          colgas="Ar",
                          msscanrange="50-1200",
                          conevolt="30")),
    
    C8serum=data.frame(c(chrominst="Waters UPLC: C8 MeOH Gradient",
                         msinst="Waters Xevo G2 TOF",
                         column="Waters C8, 1 x 100 mm, 1.7 uM",
                         solvA="95% water, 5% methanol, 0.1% formic acid",
                         solvB="5% water, 95% methanol, 0.1% formic acid",
                         MSlevs=2,
                         CE1="6",
                         CE2="15-30",
                         mstype="TOF",
                         mzdifftof=0.05,
                         msmode="P",
                         ionization="ESI",
                         ESIvoltage="2200",
                         colgas="Ar",
                         msscanrange="50-1200",
                         conevolt="30")),
    
    C18gen=data.frame(c(chrominst="Waters UPLC: C18 ACN Gradient",
                        msinst="Waters Xevo G2 QTOF",
                        column="Waters HSST3 C18, 1 x 100 mm, 1.8 uM",
                        solvA="Water, 0.1% formic acid",
                        solvB="ACN, 0.1% formic acid",
                        MSlevs=2,
                        CE1="6",
                        CE2="15-30",
                        mstype="TOF",
                        mzdifftof=0.05,
                        msmode="P",
                        ionization="ESI",
                        ESIvoltage="2200",
                        colgas="Ar",
                        msscanrange="50-1200",
                        conevolt="30")) ,
    
    PhenHexPos=data.frame(c(chrominst="Waters UPLC: ACN Gradient",
                            msinst="Waters Xevo G2 QTOF",
                            column="Waters CSH PhenylHexyl, 1 x 100 mm, 1.7 uM",
                            solvA="Water, 0.1% formic acid, 2mM AmOH",
                            solvB="ACN, 0.1% formic acid",
                            MSlevs=2,
                            CE1="6",
                            CE2="15-30",
                            mstype="TOF",
                            mzdifftof=0.05,
                            msmode="P",
                            ionization="ESI",
                            ESIvoltage="2200",
                            colgas="Ar",
                            msscanrange="50-2000",
                            conevolt="30")) ,
    
    PhenHexNeg=data.frame(c(chrominst="Waters UPLC: ACN Gradient",
                            msinst="Waters Xevo G2 QTOF",
                            column="Waters CSH PhenylHexyl, 1 x 100 mm, 1.7 uM",
                            solvA="Water, 0.1% formic acid, 2mM AmOH",
                            solvB="ACN, 0.1% formic acid",
                            MSlevs=2,
                            CE1="6",
                            CE2="15-30",
                            mstype="TOF",
                            mzdifftof=0.05,
                            msmode="N",
                            ionization="ESI",
                            ESIvoltage="2200",
                            colgas="Ar",
                            msscanrange="50-2000",
                            conevolt="30")) ,
    
    MICRO=data.frame(c(chrominst="Waters UPLC:" ,
                       msinst="Waters QTOF Micro",
                       column="Waters ",
                       solvA="",
                       solvB="",
                       MSlevs=1,
                       CE1="6",
                       CE2=NULL,
                       mstype="Q-TOF",
                       mzdifftof=0.07,
                       msmode="P",
                       ionization="ESI",
                       ESIvoltage="2200",
                       colgas="Ar",
                       msscanrange="50-1000",
                       conevolt="30")) ,
    
    GCdb5=data.frame(c(chrominst="Thermo Trace GC: TG-5MS column",
                       msinst="Thermo ISQ",
                       MSlevs=1,
                       InletTemp="280",
                       TransferTemp="280",
                       mstype="QUAD",
                       mzdiffquad=0.5,
                       msmode="P",
                       ionization="EI",
                       msscanrange="50-650",
                       scantime="0.2",
                       energy="70",
                       deriv="Methoxyamine+MSTFA")),
    
    orbi=data.frame(c(chrominst="Waters UPLC: C8 MeOH Gradient",
                      msinst="Waters Xevo G2 TOF",
                      column="Waters C8, 1 x 100 mm, 1.7 uM",
                      solvA="97% water, 1% ACN, 0.1% formic acid",
                      solvB="ACN, 0.1% formic acid",
                      MSlevs=1,
                      CE1="",
                      CE2="",
                      mstype="Orbitrap Velos Pro",
                      mzdifftof=0.05,
                      msmode="P",
                      ionization="NSI",
                      ESIvoltage="",
                      colgas="N",
                      msscanrange="100-2000",
                      conevolt="")),
    
    tqs=data.frame(c(chrominst="Waters UPLC: Sequant ZIC-pHilic",
                     msinst="Waters TQS",
                     column="Sequant ZIC-pHilic, 2 x 150 mm, 5 uM",
                     solvA="Water, 10mM AmBicarb pH 9.6",
                     solvB="ACN",
                     MSlevs=1,
                     CE1="6",
                     CE2="",
                     mstype="QQQ",
                     msmode="P",
                     ionization="ESI",
                     ESIvoltage="2200",
                     colgas="Ar",
                     msscanrange="50-1200",
                     conevolt="30")),
    
    ICP=data.frame(c(chrominst="none",
                     msinst="PerkinElmer Elan DRC ICP-MS",
                     column="none",
                     solvA="none",
                     solvB="none",
                     MSlevs=1,
                     CE1="none",
                     CE2="none",
                     mstype="Quad",
                     mzdifftof="none",
                     msmode="P",
                     ionization="ICP",
                     ESIvoltage="",
                     colgas="Ar",
                     msscanrange="",
                     conevolt="")),
    
    newLC=data.frame(c(chrominst="Waters UPLC",
                       msinst="Waters Xevo G2 TOF",
                       column="Waters C8, 1 x 100 mm, 1.7 uM",
                       MSlevs=2,
                       solvA="95% water, 5% methanol, 0.1% formic acid",
                       solvB="5% water, 95% methanol, 0.1% formic acid",
                       CE1="6",
                       CE2="15-30",
                       mstype="TOF",
                       msmode="P",
                       ionization="ESI",
                       colgas="Ar",
                       msscanrange="50-1200",
                       conevolt="30")),
    
    newGC=data.frame(c(chrominst="Thermo Trace GC: TG-5MS column",
                       msinst="Thermo ISQ",
                       MSlevs=1,
                       InletTemp="280",
                       TransferTemp="280",
                       mstype="QUAD",
                       mzdiffquad=0.5,
                       msmode="P",
                       ionization="EI",
                       msscanrange="50-650",
                       scantime="0.2",
                       energy="70",
                       deriv="Methoxyamine+MSTFA"))
  )
  
  platforms<-names(paramsets) 
  
  ExpVars<-c(Experiment="",
             Contributor="",
             Species="",
             Sample="",
             platform="",
             delim="-",
             fact1name="",
             fact2name="",
             fact3name="",
             fact4name="",
             fact5name="",
             fact6name="",
             fact7name="",
             fact8name="",
             fact9name="",
             fact10name=""
  )
  
  VarDesc<-c("experiment name, no spaces",
             "lab and or user name",
             "species name (binomial latin name)",
             "sample type",
             paste(platforms, sep=" ", collapse=" "),
             "factor delimitor in your sample names",
             "Assign a name for your factors",
             "",           
             "",           
             "",           
             "",           
             "",
             "",
             "",
             "",
             ""
  )
  
  Experiment<-data.frame(ExpVars,VarDesc, stringsAsFactors=FALSE)
  
  design<-suppressWarnings(edit(Experiment))
  
  platform<-platforms[grep(as.character(design["platform",1]), platforms, ignore.case=TRUE)]
  
  instrument<-edit(paramsets[[as.character(platform)]])
  
  exp.pars<-list(design, instrument)
  names(exp.pars)<-c("design", "instrument")
  return(exp.pars)
}
